select * from gold.fact_sales
--finding total customers by countries
select country,
COUNT(customer_key) 
from gold.dim_customers
group by country
order by 2

--finding total customer by gender
select gender,
COUNT(customer_key) as tot_customer
from gold.dim_customers
group by gender
order by 2

--finding total products by category
select category,
COUNT(product_key) as tot_product
from gold.dim_products
group by category
order by 2

--finding average cost by each category
select category,
AVG(cost) as avg_cost
from gold.dim_products
group by category
order by 2

--finding total revenue generated for each category
select category,
sum(sales_amount) as tot_sales
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by category 
order by 2

--finding total revenue generated by each customer
select c.customer_id as cust_id,
CONCAT(c.first_name, ' ',c.last_name) as full_name,
SUM(sales_amount) as total_sales  
from gold.fact_sales s
left join gold.dim_customers c
on c.customer_key = s.customer_key
group by c.customer_id,CONCAT(c.first_name, ' ',c.last_name)
order by 3 desc

--finding the distribution of sold items across countries
select c.country,
SUM(s.quantity) as quantity_sold
from gold.fact_sales s
left join gold.dim_customers c
on c.customer_key = s.customer_key
group by c.country
order by 2 desc







